[project]
name = "connect-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8>=7.3.0",
    "numpy>=2.3.5",
    "pygame>=2.6.1",
    "pytest>=9.0.1",
]
